services:
  - type: web
    name: tgcf-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PASSWORD
        value: "hocus pocus qwerty utopia"
      - key: ENVIRONMENT
        value: "production"
      - key: WEB_PORT
        value: "5000"
